// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AInput: typeof import('ant-design-vue/es')['Input']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    APopover: typeof import('ant-design-vue/es')['Popover']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    ButtonComponent: typeof import('./src/components/ButtonComponent.vue')['default']
    DemoCellRenderer: typeof import('./src/components/SjTable/DemoCellRenderer.vue')['default']
    FilterableSelect: typeof import('./src/components/FilterableSelect/FilterableSelect.vue')['default']
    LoadingOutlined: typeof import('@ant-design/icons-vue')['LoadingOutlined']
    'NavMenu.cy': typeof import('./src/components/SjBasicLayout/SjSider/NavMenu.cy.vue')['default']
    RenderTemp: typeof import('./src/components/SjBasicLayout/SjNavTab/Vue3ChromeTab/render-temp.vue')['default']
    RouterViewLoading: typeof import('./src/components/SjBasicLayout/RouterViewLoading.vue')['default']
    SjBasicLayout: typeof import('./src/components/SjBasicLayout/SjBasicLayout.vue')['default']
    SjNavTab: typeof import('./src/components/SjBasicLayout/SjNavTab/SjNavTab.vue')['default']
    SjSelectForTable: typeof import('./src/components/SjSelectForTable.vue')['default']
    SjSider: typeof import('./src/components/SjBasicLayout/SjSider/SjSider.vue')['default']
    SjTable: typeof import('./src/components/SjTable/SjTable.vue')['default']
    SjTableDemo: typeof import('./src/components/SjTable/SjTableDemo.vue')['default']
    TableComponent: typeof import('./src/components/TableComponent.vue')['default']
    TagsView: typeof import('./src/components/FilterableSelect/TagsView.vue')['default']
    Vue3TabsChrome: typeof import('./src/components/SjBasicLayout/SjNavTab/Vue3ChromeTab/vue3-tabs-chrome.vue')['default']
  }
}

export { }
